### ISSUE TITLE
nodejs 4.4.5 - RangeError: Invalid status code: 0

### ISSUE THREAD

**Issue by BlackthornYugen** [flowjs/flow.js#177]
When running on node 4.4.5 or higher I get this error in a stacktrace, 4.4.4 and below work normally. 

```
POST done desktop-animation2.gif 130620-desktop-animation2gif
_http_server.js:192
    throw new RangeError(`Invalid status code: ${statusCode}`);
    ^

RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:192:11)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:573:10)
    at ServerResponse.send (/home/media/git/flow.js/samples/Node.js/node_modules/express/lib/response.js:204:10)
    at /home/media/git/flow.js/samples/Node.js/app.js:23:31
    at /home/media/git/flow.js/samples/Node.js/flow-node.js:122:33
    at FSReqWrap.cb [as oncomplete] (fs.js:212:19)

➜ media@MEDIA-PC  ~/git/flow.js/samples/Node.js git:(master) ✗ npm version          
{ npm: '2.15.5',
  ares: '1.10.1-DEV',
  http_parser: '2.5.2',
  icu: '56.1',
  modules: '46',
  node: '4.4.5',
  openssl: '1.0.2h',
  uv: '1.8.0',
  v8: '4.5.103.35',
  zlib: '1.2.8' }
```

The error happens right after uploading a file, the client says `file could not be uploaded` but the file is successfully saved on the server before it crashes. It just seems to fail to let the client know it worked and the server crashes because the demo doesn't catch the exception.  I've tested it on my Ubuntu 14.04 media PC and my Ubuntu 16.04 laptop.

**Comment by M0J0R1S1NG** [comment]
I had the same experience and fixed it the same way.  That allowed the second and after chucnks to downlaod,  but now my chunks arent getting put back together into the file nor are they being cleaned up after.  Did you have that problem too?
